name: CICD

on: 
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        run: |
          echo "${{ secrets.APPLICATION_EC2 }}" | base64 --decode > ./src/main/resources/application-ec2.yml
          cat ./src/main/resources/application-ec2.yml
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/board .
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/board:latest
        
  deploy: 
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/board:latest
      - name: Delete old container
        run: docker rm -f board-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name board-container ${{ secrets.DOCKER_USERNAME }}/board
        
  
